version: '3'
services:

  worker:
    build:
      context: .
    volumes:
      - .:/opt/app
    depends_on:
      - redis
    command: python worker.py
    environment:
      REDIS_URL: http://redis:6379

  redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379
